//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActaApertura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActaApertura()
        {
            this.DetActaAperturas = new HashSet<DetActaApertura>();
        }
    
        public int IdActaApertura { get; set; }
        public string Correlativo { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string NumeroResolucionAutorizacion { get; set; }
        public short IdTransportista { get; set; }
        public string DocumentosSalida { get; set; }
        public System.DateTime FechaSalidaTerminal { get; set; }
        public decimal PesoSalidaTerminal { get; set; }
        public string Incidencias { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FecReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual OrdenIngreso OrdenIngreso { get; set; }
        public virtual Transportista Transportista { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetActaApertura> DetActaAperturas { get; set; }
    }
}
