//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arqueo
    {
        public int IdArqueo { get; set; }
        public int BS10 { get; set; }
        public int BS20 { get; set; }
        public int BS50 { get; set; }
        public int BS100 { get; set; }
        public int BS200 { get; set; }
        public int MS1 { get; set; }
        public int MS5 { get; set; }
        public int MS10 { get; set; }
        public int MS20 { get; set; }
        public int MS50 { get; set; }
        public int MS01 { get; set; }
        public int MS02 { get; set; }
        public int MS05 { get; set; }
        public int BD1 { get; set; }
        public int BD2 { get; set; }
        public int BD5 { get; set; }
        public int BD10 { get; set; }
        public int BD20 { get; set; }
        public int BD50 { get; set; }
        public int BD100 { get; set; }
        public int MD1 { get; set; }
        public int MD5 { get; set; }
        public int MD10 { get; set; }
        public int MD25 { get; set; }
        public int MD50 { get; set; }
        public int MD01 { get; set; }
    }
}
