//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.DetOrdenCompras = new HashSet<DetOrdenCompra>();
        }
    
        public int IdArticulo { get; set; }
        public int IdFamiliaArticulo { get; set; }
        public string NombreArticulo { get; set; }
        public short IdUnidad { get; set; }
        public decimal PNeto { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal PBruto { get; set; }
        public int IdProveedor { get; set; }
        public string Observacion { get; set; }
        public short IdCuentaContable { get; set; }
        public bool IsBaja { get; set; }
        public short IdUsuario { get; set; }
        public System.DateTime FechaReg { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual FamiliaArticulo FamiliaArticulo { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        public virtual Unidade Unidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenCompra> DetOrdenCompras { get; set; }
    }
}
