//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacionRetiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutorizacionRetiro()
        {
            this.ConstanciaEntregas = new HashSet<ConstanciaEntrega>();
            this.DetAutorizacionRetiros = new HashSet<DetAutorizacionRetiro>();
            this.Pesados = new HashSet<Pesado>();
            this.ServicioPrestados = new HashSet<ServicioPrestado>();
        }
    
        public int IdAutorizacionRetiro { get; set; }
        public string Correlativo { get; set; }
        public bool IsAduanero { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public string NumDocumentoRef { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string DuaNacionalizacion { get; set; }
        public string DuaNacionalizacionResu { get; set; }
        public System.DateTime FechaNumeracion { get; set; }
        public decimal CantidadTotal { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public decimal Fob { get; set; }
        public decimal Flete { get; set; }
        public decimal Seguro { get; set; }
        public decimal Cif { get; set; }
        public decimal MontoLiquidado { get; set; }
        public decimal MontoGarantizado { get; set; }
        public decimal MontoCancelado { get; set; }
        public System.DateTime FechaCancelacion { get; set; }
        public short IdBanco { get; set; }
        public byte Canal { get; set; }
        public System.DateTime FecReg { get; set; }
        public short IdUsuario { get; set; }
        public bool IsAnulada { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstanciaEntrega> ConstanciaEntregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetAutorizacionRetiro> DetAutorizacionRetiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pesado> Pesados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioPrestado> ServicioPrestados { get; set; }
    }
}
