//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banco()
        {
            this.AutorizacionRetiros = new HashSet<AutorizacionRetiro>();
            this.CuentaBancos = new HashSet<CuentaBanco>();
        }
    
        public short IdBanco { get; set; }
        public string NombreBanco { get; set; }
        public string Telefonos { get; set; }
        public string Email { get; set; }
        public string Sectorista { get; set; }
        public string Contacto { get; set; }
        public short IdCuentaContable { get; set; }
        public string Anexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizacionRetiro> AutorizacionRetiros { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBanco> CuentaBancos { get; set; }
    }
}
