//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasVi
    {
        public int IdCompra { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int DiasCredito { get; set; }
        public System.DateTime FechaVcto { get; set; }
        public decimal ValorVenta { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal NoGravado { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Percepcion { get; set; }
        public decimal Importe { get; set; }
        public decimal Pagado { get; set; }
        public decimal Saldo { get; set; }
        public decimal TipoCambio { get; set; }
        public string Observacion { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreTipoComprobantePago { get; set; }
        public decimal MontoAPagar { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public string CodigoTipoDocIdentidad { get; set; }
        public string CodigoMedioPago { get; set; }
        public string NombreMedioPago { get; set; }
        public string NombreCondicionPago { get; set; }
        public int IdOrdenCompra { get; set; }
        public string Correla { get; set; }
        public string NombreSeccion { get; set; }
        public string NombreArea { get; set; }
        public string NombreSubArea { get; set; }
        public short IdArea { get; set; }
        public short IdSubArea { get; set; }
        public bool IsCerrada { get; set; }
        public bool IsPagoAprobado { get; set; }
        public decimal ImporteDetraccion { get; set; }
        public System.DateTime FechaPagoDetraccion { get; set; }
        public short IdCuentaContabeDetraccion { get; set; }
        public string NombreCentroCosto { get; set; }
        public string CodigoCentroCosto { get; set; }
        public string NombreUsuario { get; set; }
        public string CodigoConcar { get; set; }
        public int IdOrdenServicio { get; set; }
        public int IdProveedor { get; set; }
        public short IdMedioPago { get; set; }
        public byte IdCondicionPago { get; set; }
        public short IdMoneda { get; set; }
        public short IdSeccion { get; set; }
        public short IdCentroCosto { get; set; }
        public short IdUsuario { get; set; }
    }
}
