//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteEgreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprobanteEgreso()
        {
            this.MovCajaBancos = new HashSet<MovCajaBanco>();
        }
    
        public int IdComprobanteEgreso { get; set; }
        public string NumdocComprobante { get; set; }
        public short IdRubro { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPago { get; set; }
        public short IdEmpleado { get; set; }
        public int IdProveedor { get; set; }
        public int IdCompra { get; set; }
        public int IdReciboHonorario { get; set; }
        public decimal Importe { get; set; }
        public decimal TipoCambio { get; set; }
        public short IdMoneda { get; set; }
        public short IdMedioPago { get; set; }
        public short IdCaja { get; set; }
        public bool IsAnulado { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual ComprobanteEgreso ComprobanteEgresos1 { get; set; }
        public virtual ComprobanteEgreso ComprobanteEgreso1 { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual MedioPago MedioPago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual MotivoAnulComprobante MotivoAnulComprobante { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        public virtual ReciboHonorario ReciboHonorario { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovCajaBanco> MovCajaBancos { get; set; }
    }
}
