//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteIngresosVi
    {
        public string NombreConcepto { get; set; }
        public string NombreMedioPago { get; set; }
        public string NombreMotivoAnulComprobante { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreCaja { get; set; }
        public string SerieFacturado { get; set; }
        public string NumdocFacturado { get; set; }
        public int IdClienteFacturado { get; set; }
        public string NombreCliente { get; set; }
        public byte IdTipoDocIdentidadCliente { get; set; }
        public string NumeroDocIdentidadCliente { get; set; }
        public string NombreCortoTipoDocIdentidadCliente { get; set; }
        public int IdComprobanteIngreso { get; set; }
        public string NumdocComprobante { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int IdFacturado { get; set; }
        public decimal Importe { get; set; }
        public short IdMedioPago { get; set; }
        public bool IsAnulado { get; set; }
        public bool IsAnticipo { get; set; }
        public decimal SaldoAnticipo { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdCaja { get; set; }
        public byte IdTipoCliente { get; set; }
        public int IdClienteComprobanteIngreso { get; set; }
        public int IdNotaDebito { get; set; }
        public decimal TipoCambio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public string NombreUsuario { get; set; }
        public string NombreRubro { get; set; }
        public short Expr1 { get; set; }
        public short IdEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public byte IdTipoDocIdentidadEmpleado { get; set; }
        public string NumeroDocIdentidadEmpleado { get; set; }
        public string CodigoTipoDocIdentidadEmpleado { get; set; }
        public string NombreCortoTipoDocIdentidadEmpleado { get; set; }
        public string CodigoMedioPago { get; set; }
        public string CodigoConcar { get; set; }
        public short IdUsuario { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
        public short IdMoneda { get; set; }
        public short IdRubro { get; set; }
    }
}
