//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstanciaEntregasVi
    {
        public int IdConstanciaEntrega { get; set; }
        public string CorrelativoConstancia { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public string ResponsableCliente { get; set; }
        public string DniResponsableCliente { get; set; }
        public short CantidadPaletas { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FecReg { get; set; }
        public string NombreUsuario { get; set; }
        public string NombreTipoRetiro { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string CorrelativoOrdenIngreso { get; set; }
        public string CorrelativoAutorizacion { get; set; }
        public System.DateTime FechaConstancia { get; set; }
        public string Ano { get; set; }
        public byte IdTipoDocIdentidadCliente { get; set; }
        public string NumeroDocIdentidadCliente { get; set; }
        public string NombreCortoTipoDocIdentidadCliente { get; set; }
        public bool IsAduanero { get; set; }
        public short IdEmpresaTransporte { get; set; }
        public short IdTransportista { get; set; }
        public byte IdTipoDocIdentidadTrasnportista { get; set; }
        public string NumeroDocIdentidadTransportista { get; set; }
        public string NombreCortoTipoDocIdentidadTransportista { get; set; }
        public string NombreTransportista { get; set; }
        public string CodigoTransportista { get; set; }
        public int IdEntregadoA { get; set; }
        public short IdResponsableDespacho { get; set; }
        public string EntregadoA { get; set; }
        public string ResponsableDespacho { get; set; }
        public decimal AreaLiberada { get; set; }
        public short IdUsuario { get; set; }
        public string DuaNacionalizacion { get; set; }
        public string Dua { get; set; }
        public System.DateTime FechaNumeracion { get; set; }
        public System.DateTime FechaCancelacion { get; set; }
        public short IdAgenciaAduanera { get; set; }
        public string CodigoAgenciaAduanera { get; set; }
        public byte IdTipoTransporte { get; set; }
        public string NombreTipoTransporte { get; set; }
        public string NombreAgenciaAduanera { get; set; }
        public string NumDocumentoRef { get; set; }
        public string DescripcionMercaderia { get; set; }
        public string NombreEmpresaTransporte { get; set; }
        public string CodigoEmpresaTransporte { get; set; }
        public byte IdTipoRetiro { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public byte Canal { get; set; }
        public string NumeroOrdenAgenciaAduanera { get; set; }
        public int IdVigilancia { get; set; }
        public short IdLicencia { get; set; }
        public string Placa { get; set; }
        public string NumeroLicencia { get; set; }
        public string NombreConductor { get; set; }
        public string DniConductor { get; set; }
        public bool IsAnulada { get; set; }
    }
}
