//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstanciaEntrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstanciaEntrega()
        {
            this.DetConstanciaEntregaAreas = new HashSet<DetConstanciaEntregaArea>();
            this.DetConstanciaEntregas = new HashSet<DetConstanciaEntrega>();
        }
    
        public int IdConstanciaEntrega { get; set; }
        public string Correlativo { get; set; }
        public System.DateTime FechaConstancia { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public int IdVigilancia { get; set; }
        public int IdEntregadoA { get; set; }
        public short IdResponsableDespacho { get; set; }
        public short IdTransportista { get; set; }
        public decimal AreaLiberada { get; set; }
        public string DniResponsableCliente { get; set; }
        public string ResponsableCliente { get; set; }
        public byte IdTipoRetiro { get; set; }
        public short CantidadPaletas { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FecReg { get; set; }
        public short IdUsuario { get; set; }
        public bool IsAnulada { get; set; }
    
        public virtual AutorizacionRetiro AutorizacionRetiro { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual TipoRetiro TipoRetiro { get; set; }
        public virtual Transportista Transportista { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vigilancia Vigilancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetConstanciaEntregaArea> DetConstanciaEntregaAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetConstanciaEntrega> DetConstanciaEntregas { get; set; }
    }
}
