//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.ContratoNaves = new HashSet<ContratoNave>();
            this.CuentaCorrientes = new HashSet<CuentaCorriente>();
            this.Facturados = new HashSet<Facturado>();
        }
    
        public int IdContrato { get; set; }
        public string Correlativo { get; set; }
        public short Renovacion { get; set; }
        public int IdCotizacion { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public short IdMoneda { get; set; }
        public decimal Area { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal ImporteTotal { get; set; }
        public string Observacion { get; set; }
        public decimal TarifaServicioExtraordinarioHora { get; set; }
        public decimal TarifaDescarga20 { get; set; }
        public decimal TarifaDescarga40 { get; set; }
        public decimal TarifaMontaCarga { get; set; }
        public bool IsAnulado { get; set; }
        public short IdMotivoAnulContrato { get; set; }
        public bool IsEnviado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoNave> ContratoNaves { get; set; }
        public virtual MotivoAnulContrato MotivoAnulContrato { get; set; }
        public virtual Cotizacione Cotizacione { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCorriente> CuentaCorrientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturado> Facturados { get; set; }
    }
}
