//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativoComprobante
    {
        public int IdCorrelativoComprobantePago { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public string Serie { get; set; }
        public string NumeroCorrelativo { get; set; }
        public string SerieNotaBol { get; set; }
        public string NumeroCorrelativoNotaBol { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual TipoComprobantePago TipoComprobantePago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
