//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacione()
        {
            this.Contratos = new HashSet<Contrato>();
            this.HistorialCotizaciones = new HashSet<HistorialCotizacione>();
        }
    
        public int IdCotizacion { get; set; }
        public string Correlativo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCliente { get; set; }
        public string Atencion { get; set; }
        public string Referencia { get; set; }
        public short IdEmpleado { get; set; }
        public short IdAgente { get; set; }
        public decimal Area { get; set; }
        public short IdMoneda { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal FacturacionMinimaMes { get; set; }
        public decimal TarifaPaleta { get; set; }
        public decimal PorcTarifaSegurorMes { get; set; }
        public decimal TarifaMinimaSeguroMes { get; set; }
        public decimal TarifaDescarga20 { get; set; }
        public decimal TarifaDescarga40 { get; set; }
        public decimal TarifaCargaPlataforma { get; set; }
        public decimal TarifaCargaFurgones { get; set; }
        public decimal TarifaCargaRacks { get; set; }
        public decimal TarifaCargaPisoPaletas { get; set; }
        public decimal TarifaServicioExtraordinarioHora { get; set; }
        public decimal PrecioUnitarioPaletizado { get; set; }
        public decimal PrecioUnitarioPicking { get; set; }
        public decimal TarifaMinimaServicioAdicional { get; set; }
        public bool IsAnulada { get; set; }
        public bool IsEnviada { get; set; }
        public bool IsAceptada { get; set; }
        public byte[] ImagenAceptacion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual Agente Agente { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCotizacione> HistorialCotizaciones { get; set; }
    }
}
