//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorriente
    {
        public int IdCuentaCorriente { get; set; }
        public System.DateTime FechaFacturacion { get; set; }
        public int IdContrato { get; set; }
        public int IdFacturado { get; set; }
        public decimal Importe { get; set; }
        public string DetalleFac { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Facturado Facturado { get; set; }
    }
}
