//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesglosesVi
    {
        public int IdDesglose { get; set; }
        public decimal CantidadOrigen { get; set; }
        public decimal CantidadDestino { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreUsuario { get; set; }
        public int IdProducto { get; set; }
        public string CodigoProducto { get; set; }
        public short IdUnidadBulto { get; set; }
        public string DescripcionProducto1 { get; set; }
        public int IdProductoDestino { get; set; }
        public short IdUnidadBultoDestino { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string Correlativo { get; set; }
        public string Ano { get; set; }
        public string NombreUnidadBultoDestino { get; set; }
        public string NombreUnidadBultoOrigen { get; set; }
        public int IdDetOrdenIngresoOrigen { get; set; }
        public int IdDetOrdenIngresoDestino { get; set; }
        public short IdUsuario { get; set; }
    }
}
