//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetActaApertura
    {
        public int IdDetActaApertura { get; set; }
        public int IdActaApertura { get; set; }
        public int IdGuiaRemision { get; set; }
    
        public virtual ActaApertura ActaApertura { get; set; }
        public virtual GuiaRemision GuiaRemision { get; set; }
    }
}
