//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetBancoCobroPagosVi
    {
        public int IdDetBancoCobroPago { get; set; }
        public int IdBancoCobroPago { get; set; }
        public string Descripcion { get; set; }
        public string Anexo { get; set; }
        public decimal Importe { get; set; }
        public int IdFacturado { get; set; }
        public int IdNotaDebito { get; set; }
        public int IdCompra { get; set; }
        public int IdReciboHonorario { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public short IdMoneda { get; set; }
        public decimal TipoCambio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NumeroCuentaContableBco { get; set; }
        public string CodigoCentroCosto { get; set; }
        public byte IdTipoComprobantePagoFacturado { get; set; }
        public string CodigoConcarFacturado { get; set; }
        public byte IdTipoComprobantePagoCompra { get; set; }
        public string CodigoConcarCompra { get; set; }
        public string Area { get; set; }
        public string SubDiario { get; set; }
        public bool IsCobro { get; set; }
        public bool IsAnulado { get; set; }
        public short IdCuentaBanco { get; set; }
        public string NumMov { get; set; }
        public string NumCuenta { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreRubro { get; set; }
        public short IdRubro { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public short IdBanco { get; set; }
        public string NombreBanco { get; set; }
        public string NumeroCuentaContableDet { get; set; }
        public short IdCentroCosto { get; set; }
        public short IdCuentaContable { get; set; }
    }
}
