//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetConstanciaEntregasVi
    {
        public int IdDetConstanciaEntrega { get; set; }
        public int IdConstanciaEntrega { get; set; }
        public int IdDetAutorizacionRetiro { get; set; }
        public short CantidadPaletas { get; set; }
        public string Observacion { get; set; }
        public int IdDetOrdenIngreso { get; set; }
        public int IdProducto { get; set; }
        public string DescripcionProducto1 { get; set; }
        public string DescripcionProducto2 { get; set; }
        public string DescripcionProducto3 { get; set; }
        public string DescripcionProducto4 { get; set; }
        public string DescripcionProducto5 { get; set; }
        public short IdUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public string CodigoProducto { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public string DuaNacionalizacionResu { get; set; }
        public string CorrelativoOrdenIngreso { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadBulto { get; set; }
        public decimal CantidadFisica { get; set; }
        public string Correlativo { get; set; }
        public string SeriePoliza { get; set; }
        public string PartidaArancelaria { get; set; }
        public decimal Fob { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal Cif { get; set; }
        public string NombreFamiliaProducto { get; set; }
        public short IdFamiliaProducto { get; set; }
        public System.DateTime FechaConstancia { get; set; }
        public int IdCliente { get; set; }
        public string Ano { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string NumDocumentoRefAR { get; set; }
        public string NombreCliente { get; set; }
        public string CorrelativoAutorizacionRetiro { get; set; }
        public short IdNave { get; set; }
        public string CodigoNave { get; set; }
        public bool IsAduanero { get; set; }
        public string Dua { get; set; }
        public string NumeroDocumentoRefOI { get; set; }
        public string NombreClienteEntregadoA { get; set; }
        public int IdEntregadoA { get; set; }
        public int IdVigilancia { get; set; }
        public string Placa { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public string SerieGuia { get; set; }
        public string NumeroGuia { get; set; }
    }
}
