//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetComprasVi
    {
        public int IdDetalleCompra { get; set; }
        public int IdCompra { get; set; }
        public int IdArticulo { get; set; }
        public decimal ValorCompra { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal Cantidad { get; set; }
        public decimal DctoPorc { get; set; }
        public decimal TotalItem { get; set; }
        public int IdFamiliaArticulo { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaVcto { get; set; }
        public short IdMedioPago { get; set; }
        public short IdMoneda { get; set; }
        public string CodigoMedioPago { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public decimal TipoCambio { get; set; }
        public string Observacion { get; set; }
        public int IdProveedor { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string CodigoCentroCosto { get; set; }
        public bool IsAnulado { get; set; }
        public string NombreArticulo { get; set; }
        public short IdCuentaContable { get; set; }
        public string NumeroCuentaContable { get; set; }
        public string NombreCuentaContable { get; set; }
        public decimal ImporteTotalDoc { get; set; }
        public decimal MontoIgvTotalDoc { get; set; }
        public bool IsCerrada { get; set; }
        public string NombreCentroCosto { get; set; }
        public short Expr1 { get; set; }
        public decimal ValorVenta { get; set; }
        public decimal ImporteDetraccion { get; set; }
        public System.DateTime FechaPagoDetraccion { get; set; }
        public short IdCuentaContabeDetraccion { get; set; }
        public short IdUnidad { get; set; }
        public string NombreUnidad { get; set; }
        public string NombreFamiliaArticulo { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
    }
}
