//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetFacturado
    {
        public int IdDetFacturado { get; set; }
        public int IdFacturado { get; set; }
        public short IdRubro { get; set; }
        public string Observacion { get; set; }
        public decimal Cantidad { get; set; }
        public short IdUnidad { get; set; }
        public decimal ValorVentaUnit { get; set; }
        public decimal SubTotalVenta { get; set; }
        public decimal DctoPorc { get; set; }
        public decimal TotDctoItem { get; set; }
        public decimal ValorVentaTotal { get; set; }
        public byte IdTipoIgv { get; set; }
        public decimal PorcIgvItem { get; set; }
        public decimal MontoIgvItem { get; set; }
        public decimal TotalItem { get; set; }
        public int IdFacturadoAnticipo { get; set; }
    
        public virtual Facturado Facturado { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual TipoIgv TipoIgv { get; set; }
        public virtual Unidade Unidade { get; set; }
    }
}
