//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetGuiaRemisionsVi
    {
        public int IdDetGuiaRemision { get; set; }
        public int IdGuiaRemision { get; set; }
        public int IdDetOrdenIngreso { get; set; }
        public decimal CantidadBuenos { get; set; }
        public decimal CantidadMalos { get; set; }
        public decimal CantidadBultos { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public short CantidadPaletas { get; set; }
        public int IdOrdenIngreso { get; set; }
        public int IdProducto { get; set; }
        public short IdEmpresaTransporte { get; set; }
        public string NombreEmpresaTransporte { get; set; }
        public string NombreTipoIngreso { get; set; }
        public int IdCliente { get; set; }
        public short IdFamiliaProducto { get; set; }
        public string NombreFamiliaProducto { get; set; }
        public string NombreCliente { get; set; }
        public string SerieGuia { get; set; }
        public string NumeroGuia { get; set; }
        public int IdDetVigilanciaGuia { get; set; }
        public int IdVigilancia { get; set; }
        public string Placa { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public string DescripcionProducto1 { get; set; }
        public string CodigoProducto { get; set; }
        public short IdNave { get; set; }
        public string CodigoNave { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool IsAduanero { get; set; }
        public string Correlativo { get; set; }
        public string Ano { get; set; }
        public string NumeroDocumentoRef { get; set; }
        public short IdUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public string SeriePoliza { get; set; }
        public string Observacion { get; set; }
        public string AbrevNombreTipoIngreso { get; set; }
        public short IdZona { get; set; }
        public string CodigoZona { get; set; }
        public byte IdTipoIngreso { get; set; }
    }
}
