//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetHistorialCotizacione
    {
        public int IdDetHistorialCotizacion { get; set; }
        public int IdHistorialCotizacion { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FecReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual HistorialCotizacione HistorialCotizacione { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
