//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetNotaCreditosVi
    {
        public int IdDetNotaCredito { get; set; }
        public int IdNotaCredito { get; set; }
        public int IdRubro { get; set; }
        public string Observacion { get; set; }
        public decimal Cantidad { get; set; }
        public decimal ValorVentaUnit { get; set; }
        public decimal SubTotalVenta { get; set; }
        public decimal DctoPorc { get; set; }
        public decimal TotDctoItem { get; set; }
        public decimal ValorVentaTotal { get; set; }
        public int IdTipoIgv { get; set; }
        public decimal PorcIgvItem { get; set; }
        public decimal MontoIgvItem { get; set; }
        public decimal TotalItem { get; set; }
        public string NombreRubro { get; set; }
        public short IdCuentaContable { get; set; }
        public string NumeroCuentaContable { get; set; }
        public string NombreCuentaContable { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal TipoCambio { get; set; }
        public int IdTipoNotaCredito { get; set; }
        public int IdFacturado { get; set; }
        public decimal TotalNotaCredito { get; set; }
        public int IdTipoComprobantePago { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public decimal Exonerado { get; set; }
        public decimal Inafecto { get; set; }
        public decimal Gravado { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal Expr3 { get; set; }
        public decimal Expr4 { get; set; }
        public decimal Expr5 { get; set; }
        public decimal Expr6 { get; set; }
        public string NombreCliente { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public short IdMoneda { get; set; }
        public short IdUnidad { get; set; }
    }
}
