//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenIngreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetOrdenIngreso()
        {
            this.Desgloses = new HashSet<Desglos>();
            this.DetAutorizacionRetiros = new HashSet<DetAutorizacionRetiro>();
            this.DetGuiaRemisions = new HashSet<DetGuiaRemision>();
        }
    
        public int IdDetOrdenIngreso { get; set; }
        public int IdOrdenIngreso { get; set; }
        public short IdNave { get; set; }
        public short IdZona { get; set; }
        public int IdProducto { get; set; }
        public string DescripcionProducto1 { get; set; }
        public string DescripcionProducto2 { get; set; }
        public string DescripcionProducto3 { get; set; }
        public string DescripcionProducto4 { get; set; }
        public string DescripcionProducto5 { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public short IdUnidadBulto { get; set; }
        public decimal CantidadBulto { get; set; }
        public decimal CantidadDispBultoGuia { get; set; }
        public decimal CantidadDispBultoAutRet { get; set; }
        public short IdUnidadComercial { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadDispComGuia { get; set; }
        public decimal CantidadDispComAutRet { get; set; }
        public short IdUnidadFisica { get; set; }
        public decimal CantidadFisica { get; set; }
        public decimal CantidadDispFisGuia { get; set; }
        public decimal CantidadDispFisAutRet { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoBrutoDispAutRet { get; set; }
        public decimal PesoNeto { get; set; }
        public decimal Fob { get; set; }
        public decimal FobDispAutRet { get; set; }
        public decimal Flete { get; set; }
        public decimal FleteDispAutRet { get; set; }
        public decimal Seguro { get; set; }
        public decimal SeguroDispAutRet { get; set; }
        public decimal Cif { get; set; }
        public decimal CifDispAutRet { get; set; }
        public byte IdTipoMercaderia { get; set; }
        public string SeriePoliza { get; set; }
        public string FacturaComercial { get; set; }
        public Nullable<System.DateTime> FechaFacturaComercial { get; set; }
        public string NumDocTransporte { get; set; }
        public string PartidaArancelaria { get; set; }
        public bool IsDesglose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desglos> Desgloses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetAutorizacionRetiro> DetAutorizacionRetiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetGuiaRemision> DetGuiaRemisions { get; set; }
        public virtual Nave Nave { get; set; }
        public virtual OrdenIngreso OrdenIngreso { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual TipoMercaderia TipoMercaderia { get; set; }
        public virtual UnidadBulto UnidadBulto { get; set; }
        public virtual UnidadComerciale UnidadComerciale { get; set; }
        public virtual UnidadFisica UnidadFisica { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
