//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenIngresoCertificadoDeposito
    {
        public int IdDetOrdenIngresoCertificadoDeposito { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string Correlativo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual OrdenIngreso OrdenIngreso { get; set; }
    }
}
