//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenIngresoArea
    {
        public int IdDetOrdenIngresoArea { get; set; }
        public int IdOrdenIngreso { get; set; }
        public short IdNave { get; set; }
        public decimal AreaOcupada { get; set; }
        public System.DateTime FechaFacturacion { get; set; }
        public int IdFacturado { get; set; }
        public string DocumentoFuente { get; set; }
        public short IdResponsable { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Facturado Facturado { get; set; }
        public virtual Nave Nave { get; set; }
        public virtual OrdenIngreso OrdenIngreso { get; set; }
    }
}
