//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenIngresoAreasVi
    {
        public int IdDetOrdenIngresoArea { get; set; }
        public int IdOrdenIngreso { get; set; }
        public short IdNave { get; set; }
        public decimal AreaOcupada { get; set; }
        public string NombreCliente { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string NombreNave { get; set; }
        public System.DateTime FechaFacturacion { get; set; }
        public int IdFacturado { get; set; }
        public string DescripcionMercaderia { get; set; }
        public bool IsAduanero { get; set; }
        public string Correlativo { get; set; }
        public string Ano { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public int DiasPago { get; set; }
        public bool IsCerrada { get; set; }
        public string Dua { get; set; }
        public string Observacion { get; set; }
        public string NumeroDocumentoRef { get; set; }
        public string DocumentoFuente { get; set; }
        public short IdResponsable { get; set; }
        public string NombreEmpleado { get; set; }
    }
}
