//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetPagoPersonale
    {
        public int IdDetPagoPersonales { get; set; }
        public int IdPagoPersonal { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Pago { get; set; }
        public short IdMedioPago { get; set; }
        public short IdCaja { get; set; }
        public bool IsAnulado { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual MedioPago MedioPago { get; set; }
        public virtual PagoPersonale PagoPersonale { get; set; }
    }
}
