//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetVigilanciaGuia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetVigilanciaGuia()
        {
            this.GuiaRemisions = new HashSet<GuiaRemision>();
            this.Pesados = new HashSet<Pesado>();
        }
    
        public int IdDetVigilanciaGuia { get; set; }
        public int IdVigilancia { get; set; }
        public string SerieGuia { get; set; }
        public string NumeroGuia { get; set; }
        public int IdDetAutorizacionRetiro { get; set; }
    
        public virtual DetAutorizacionRetiro DetAutorizacionRetiro { get; set; }
        public virtual Vigilancia Vigilancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiaRemision> GuiaRemisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pesado> Pesados { get; set; }
    }
}
