//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionCliente
    {
        public short IdDireccionCliente { get; set; }
        public int IdCliente { get; set; }
        public string NombreDireccionCliente { get; set; }
        public string IdDpto { get; set; }
        public string IdProv { get; set; }
        public string IdUbigeo { get; set; }
        public bool IsFiscal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
