//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.ComprobanteEgresos = new HashSet<ComprobanteEgreso>();
            this.ComprobanteIngresos = new HashSet<ComprobanteIngreso>();
            this.ConstanciaEntregas = new HashSet<ConstanciaEntrega>();
            this.Cotizaciones = new HashSet<Cotizacione>();
            this.DetOrdenIngresoAreas = new HashSet<DetOrdenIngresoArea>();
            this.GuiaRemisions = new HashSet<GuiaRemision>();
            this.PagoPersonales = new HashSet<PagoPersonale>();
            this.RequerimientoProductos = new HashSet<RequerimientoProducto>();
        }
    
        public short IdEmpleado { get; set; }
        public short IdCargo { get; set; }
        public short IdGrupoPago { get; set; }
        public string NombreEmpleado { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteEgreso> ComprobanteEgresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteIngreso> ComprobanteIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstanciaEntrega> ConstanciaEntregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacione> Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngresoArea> DetOrdenIngresoAreas { get; set; }
        public virtual GrupoPago GrupoPago { get; set; }
        public virtual TipoDocIdentidade TipoDocIdentidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiaRemision> GuiaRemisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoPersonale> PagoPersonales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequerimientoProducto> RequerimientoProductos { get; set; }
    }
}
