//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaTransportesVi
    {
        public string NombreEmpresaTransporte { get; set; }
        public string CodigoEmpresaTransporte { get; set; }
        public string NombreTipoTransporte { get; set; }
        public short IdEmpresaTransporte { get; set; }
        public byte IdTipoTransporte { get; set; }
    }
}
