//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaRemision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuiaRemision()
        {
            this.DetActaAperturas = new HashSet<DetActaApertura>();
            this.DetGuiaRemisions = new HashSet<DetGuiaRemision>();
        }
    
        public int IdGuiaRemision { get; set; }
        public int IdOrdenIngreso { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int IdDetVigilanciaGuia { get; set; }
        public string Observacion { get; set; }
        public string NumeroContenedor { get; set; }
        public string PrecintoOrigen { get; set; }
        public string PrecintoSupervision { get; set; }
        public string PrecintoAduana { get; set; }
        public byte IdTipoContenedor { get; set; }
        public short CantidadPaletas { get; set; }
        public short IdAtendidoPor { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public decimal BultosDeclarados { get; set; }
        public decimal CantidadBuenos { get; set; }
        public decimal CantidadMalos { get; set; }
        public decimal CantidadBultos { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetActaApertura> DetActaAperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetGuiaRemision> DetGuiaRemisions { get; set; }
        public virtual DetVigilanciaGuia DetVigilanciaGuia { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual OrdenIngreso OrdenIngreso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
