//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventariosVi
    {
        public int IdInventario { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreSeccion { get; set; }
        public decimal ValorInventario { get; set; }
        public System.DateTime FechaInventarioFinal { get; set; }
        public Nullable<System.DateTime> FechaInventarioInicial { get; set; }
        public string NombreUsuario { get; set; }
        public short IdSeccion { get; set; }
        public short IdUsuario { get; set; }
    }
}
