//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovCajaBanco
    {
        public int IdMovCajaBanco { get; set; }
        public System.DateTime FechaMov { get; set; }
        public int IdComprobanteIngreso { get; set; }
        public int IdComprobanteEgreso { get; set; }
    
        public virtual ComprobanteEgreso ComprobanteEgreso { get; set; }
        public virtual ComprobanteIngreso ComprobanteIngreso { get; set; }
    }
}
