//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nave()
        {
            this.ContratoNaves = new HashSet<ContratoNave>();
            this.DetConstanciaEntregaAreas = new HashSet<DetConstanciaEntregaArea>();
            this.DetOrdenIngresoAreaKardexs = new HashSet<DetOrdenIngresoAreaKardex>();
            this.DetOrdenIngresoAreas = new HashSet<DetOrdenIngresoArea>();
            this.DetOrdenIngresos = new HashSet<DetOrdenIngreso>();
            this.InventarioNaves = new HashSet<InventarioNave>();
            this.OrdenIngresos = new HashSet<OrdenIngreso>();
            this.TransferenciaNaves = new HashSet<TransferenciaNave>();
            this.TransferenciaNaves1 = new HashSet<TransferenciaNave>();
        }
    
        public short IdNave { get; set; }
        public string NombreNave { get; set; }
        public string CodigoNave { get; set; }
        public decimal AreaFisica { get; set; }
        public decimal AreaTransito { get; set; }
        public decimal AreaPasillo { get; set; }
        public decimal AreaAforo { get; set; }
        public decimal AreaOtros { get; set; }
        public decimal AreaTotalDisponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoNave> ContratoNaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetConstanciaEntregaArea> DetConstanciaEntregaAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngresoAreaKardex> DetOrdenIngresoAreaKardexs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngresoArea> DetOrdenIngresoAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngreso> DetOrdenIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioNave> InventarioNaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenIngreso> OrdenIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaNave> TransferenciaNaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaNave> TransferenciaNaves1 { get; set; }
    }
}
