//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaCredito()
        {
            this.DetNotaCreditos = new HashSet<DetNotaCredito>();
            this.NotaCreditoFacAplicados = new HashSet<NotaCreditoFacAplicado>();
        }
    
        public int IdNotaCredito { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public byte IdTipoNotaCredito { get; set; }
        public decimal TipoCambio { get; set; }
        public int IdFacturado { get; set; }
        public decimal DctoItems { get; set; }
        public decimal DctoPorc { get; set; }
        public decimal DctoTotal { get; set; }
        public decimal Exonerado { get; set; }
        public decimal Inafecto { get; set; }
        public decimal Gravado { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal Anticipo { get; set; }
        public decimal OtrosCargos { get; set; }
        public decimal Gratuito { get; set; }
        public decimal Total { get; set; }
        public decimal MontoAplicado { get; set; }
        public decimal SaldoPorAplicar { get; set; }
        public string Observacion { get; set; }
        public bool IsAnulado { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetNotaCredito> DetNotaCreditos { get; set; }
        public virtual Facturado Facturado { get; set; }
        public virtual MotivoAnulComprobante MotivoAnulComprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCreditoFacAplicado> NotaCreditoFacAplicados { get; set; }
        public virtual TipoNotaCredito TipoNotaCredito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
