//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoPersonale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagoPersonale()
        {
            this.DetPagoPersonales = new HashSet<DetPagoPersonale>();
        }
    
        public int IdPagoPersonal { get; set; }
        public System.DateTime FechaProg { get; set; }
        public short IdEmpleado { get; set; }
        public decimal Importe { get; set; }
        public decimal Pagado { get; set; }
        public decimal Saldo { get; set; }
        public string Observacion { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public short IdMotivoAnulPagoPersonal { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetPagoPersonale> DetPagoPersonales { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual MotivoAnulPagoPersonale MotivoAnulPagoPersonale { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
