//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesadosVi
    {
        public string CorrelativoPesado { get; set; }
        public decimal PesoIngreso { get; set; }
        public decimal PesoSalida { get; set; }
        public decimal PesoNeto { get; set; }
        public System.DateTime FecReg { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string CorrelativoOrdenIngreso { get; set; }
        public string AnoOrdenIngreso { get; set; }
        public string Placa { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public string CorrelativoAutorizacionRetiro { get; set; }
        public string NombreUsuario { get; set; }
        public int IdVigilancia { get; set; }
        public string SerieGuia { get; set; }
        public string NumeroGuia { get; set; }
        public int IdDetVigilanciaGuiaPesados { get; set; }
        public int IdPesado { get; set; }
        public decimal CantidadBultosOrdenIngreso { get; set; }
        public short IdUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string DocRefParticular { get; set; }
        public System.DateTime FechaPesadoIngreso { get; set; }
        public System.DateTime FechaPesadoSalida { get; set; }
        public string NumeroDocumentoRefOrdenIngreso { get; set; }
        public string NumDocumentoRefAutorizacionRetiro { get; set; }
        public string DescripcionMercaderia { get; set; }
        public bool IsAduanero { get; set; }
        public byte TipoPesado { get; set; }
        public short IdUsuario { get; set; }
        public byte TipoOperacion { get; set; }
    }
}
