//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pesado
    {
        public int IdPesado { get; set; }
        public string Correlativo { get; set; }
        public byte TipoPesado { get; set; }
        public int IdVigilancia { get; set; }
        public int IdDetVigilanciaGuia { get; set; }
        public int IdOrdenIngreso { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public System.DateTime FechaPesadoIngreso { get; set; }
        public System.DateTime FechaPesadoSalida { get; set; }
        public decimal PesoIngreso { get; set; }
        public decimal PesoSalida { get; set; }
        public decimal PesoNeto { get; set; }
        public string DocRefParticular { get; set; }
        public System.DateTime FecReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual AutorizacionRetiro AutorizacionRetiro { get; set; }
        public virtual DetVigilanciaGuia DetVigilanciaGuia { get; set; }
        public virtual OrdenIngreso OrdenIngreso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
