//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosVi
    {
        public int IdProducto { get; set; }
        public int IdCliente { get; set; }
        public string CodigoProducto { get; set; }
        public string Descripcion1 { get; set; }
        public string Descripcion2 { get; set; }
        public string Descripcion3 { get; set; }
        public string Descripcion4 { get; set; }
        public string Descripcion5 { get; set; }
        public short IdUnidad { get; set; }
        public string NombreCliente { get; set; }
        public string NombreTipoMercaderia { get; set; }
        public string NombreUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public string NombreFamiliaProducto { get; set; }
        public byte IdTipoMercaderia { get; set; }
        public short IdFamiliaProducto { get; set; }
    }
}
