//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboHonorario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReciboHonorario()
        {
            this.ComprobanteEgresos = new HashSet<ComprobanteEgreso>();
            this.DetBancoCobroPagos = new HashSet<DetBancoCobroPago>();
        }
    
        public int IdReciboHonorario { get; set; }
        public string Numdoc { get; set; }
        public int IdProveedor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Importe { get; set; }
        public short IdCuentaContabeRecibo { get; set; }
        public decimal ImporteRetenido { get; set; }
        public System.DateTime FechaPagoRetencion { get; set; }
        public short IdCuentaContabeRetencion { get; set; }
        public decimal Pagado { get; set; }
        public decimal Saldo { get; set; }
        public decimal MontoAPagar { get; set; }
        public short IdMoneda { get; set; }
        public decimal TipoCambio { get; set; }
        public string Glosa { get; set; }
        public string Observacion { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsPagoAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteEgreso> ComprobanteEgresos { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual CuentaContable CuentaContable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetBancoCobroPago> DetBancoCobroPagos { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
