//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequerimientoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequerimientoProducto()
        {
            this.DetRequerimientoProductos = new HashSet<DetRequerimientoProducto>();
            this.OrdenCompras = new HashSet<OrdenCompra>();
        }
    
        public int IdRequerimientoProducto { get; set; }
        public string NumReqProd { get; set; }
        public System.DateTime FechaRequerimiento { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public short IdEmpleado { get; set; }
        public short IdSeccion { get; set; }
        public decimal MontoTotalReferencial { get; set; }
        public string Observacion { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAtendido { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetRequerimientoProducto> DetRequerimientoProductos { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompra> OrdenCompras { get; set; }
        public virtual Seccione Seccione { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
