//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubrosVi
    {
        public short IdRubro { get; set; }
        public string NombreRubro { get; set; }
        public bool IsServicio { get; set; }
        public bool IsNoCobrarFacBloque { get; set; }
        public short IdCuentaContable { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool IsIngreso { get; set; }
        public short Expr1 { get; set; }
        public string NumeroCuentaContable { get; set; }
        public string NombreConcepto { get; set; }
        public short IdUsuario { get; set; }
        public short IdConcepto { get; set; }
        public bool IsDefaultFacturacion { get; set; }
        public decimal PorcDetraccion { get; set; }
    }
}
