//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rubro()
        {
            this.BancoCobroPagos = new HashSet<BancoCobroPago>();
            this.ComprobanteEgresos = new HashSet<ComprobanteEgreso>();
            this.ComprobanteIngresos = new HashSet<ComprobanteIngreso>();
            this.DetFacturados = new HashSet<DetFacturado>();
            this.DetNotaCreditos = new HashSet<DetNotaCredito>();
            this.Parametros = new HashSet<Parametro>();
            this.ServicioPrestados = new HashSet<ServicioPrestado>();
            this.Tarifas = new HashSet<Tarifa>();
        }
    
        public short IdRubro { get; set; }
        public string NombreRubro { get; set; }
        public bool IsDefaultFacturacion { get; set; }
        public bool IsServicio { get; set; }
        public bool IsNoCobrarFacBloque { get; set; }
        public short IdConcepto { get; set; }
        public short IdCuentaContable { get; set; }
        public decimal PorcDetraccion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancoCobroPago> BancoCobroPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteEgreso> ComprobanteEgresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteIngreso> ComprobanteIngresos { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetFacturado> DetFacturados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetNotaCredito> DetNotaCreditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametro> Parametros { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioPrestado> ServicioPrestados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa> Tarifas { get; set; }
    }
}
