//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioPrestadosVi
    {
        public int IdServicioPrestado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdOrdenIngreso { get; set; }
        public short IdRubro { get; set; }
        public int IdFacturado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string CorrelativoOrdenIngreso { get; set; }
        public string Ano { get; set; }
        public int IdClienteOI { get; set; }
        public string NombreClienteOI { get; set; }
        public byte IdTipoDocIdentidadOI { get; set; }
        public string NumeroDocIdentidadOI { get; set; }
        public string NombreRubro { get; set; }
        public string NombreConcepto { get; set; }
        public string NombreUsuario { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public string NombreTipoComprobantePago { get; set; }
        public string Observacion { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioNetoUnitatio { get; set; }
        public decimal ImporteTotal { get; set; }
        public short IdUsuario { get; set; }
        public string NombreMoneda { get; set; }
        public string CodigoMoneda { get; set; }
        public string SimboloMoneda { get; set; }
        public string Correlativo { get; set; }
        public string DescripcionMercaderiaOI { get; set; }
        public short IdMoneda { get; set; }
        public short IdResponsable { get; set; }
        public string NombreEmpleado { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public byte TipoServicio { get; set; }
        public decimal CantidadBultosOI { get; set; }
        public string NumeroDocumentoRefOI { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public decimal CantidadBultosAR { get; set; }
        public string DescripcionMercaderiaOIAR { get; set; }
        public bool IsAduanero { get; set; }
        public string DuaNacionalizacionResu { get; set; }
        public string NombreUsuarioApruebaAnula { get; set; }
        public short IdUsuarioApruebaAnula { get; set; }
        public string NombreClienteAR { get; set; }
        public string NumeroDocIdentidadAR { get; set; }
        public byte IdTipoDocIdentidadAR { get; set; }
        public string NombreCortoTipoDocIdentidadAR { get; set; }
        public string CorrelativoAR { get; set; }
        public int IdClienteAR { get; set; }
        public string NumeroDocumentoRefOIAR { get; set; }
        public string NumDocumentoRefAR { get; set; }
    }
}
