//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transportista()
        {
            this.ActaAperturas = new HashSet<ActaApertura>();
            this.ConstanciaEntregas = new HashSet<ConstanciaEntrega>();
        }
    
        public short IdTransportista { get; set; }
        public string CodigoTransportista { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string NombreTransportista { get; set; }
        public string DireccionTransportista { get; set; }
        public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActaApertura> ActaAperturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstanciaEntrega> ConstanciaEntregas { get; set; }
        public virtual TipoDocIdentidade TipoDocIdentidade { get; set; }
    }
}
