//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancoCobroPagosVi
    {
        public string NombreUsuario { get; set; }
        public string NombreRubro { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreBanco { get; set; }
        public string NumCuenta { get; set; }
        public int IdBancoCobroPago { get; set; }
        public bool IsCobro { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal TipoCambio { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool IsAnulado { get; set; }
        public string NumMov { get; set; }
        public string CorrelativoManualConcar { get; set; }
        public string SubDiario { get; set; }
        public decimal Importe { get; set; }
        public string NumeroCuentaContable { get; set; }
        public string Anexo { get; set; }
        public string Area { get; set; }
        public short IdCuentaBanco { get; set; }
        public short IdBanco { get; set; }
        public short IdRubro { get; set; }
        public short IdUsuario { get; set; }
        public short IdMoneda { get; set; }
        public short IdCuentaContable { get; set; }
    }
}
