//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.AutorizacionRetiros = new HashSet<AutorizacionRetiro>();
            this.ComprobanteIngresos = new HashSet<ComprobanteIngreso>();
            this.ConstanciaEntregas = new HashSet<ConstanciaEntrega>();
            this.Contratos = new HashSet<Contrato>();
            this.Cotizaciones = new HashSet<Cotizacione>();
            this.DetClienteContactos = new HashSet<DetClienteContacto>();
            this.DireccionClientes = new HashSet<DireccionCliente>();
            this.Facturados = new HashSet<Facturado>();
            this.InventarioNaves = new HashSet<InventarioNave>();
            this.OrdenIngresos = new HashSet<OrdenIngreso>();
            this.Productos = new HashSet<Producto>();
            this.Tarifas = new HashSet<Tarifa>();
            this.TransferenciaNaves = new HashSet<TransferenciaNave>();
            this.Vigilancias = new HashSet<Vigilancia>();
        }
    
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public byte IdTipoCliente { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string PartidaElectrónica { get; set; }
        public string RepresentanteLegal { get; set; }
        public string DniRepresentanteLegal { get; set; }
        public short IdPais { get; set; }
        public string Telefono { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public int DiasPago { get; set; }
        public string CuentaDetraccion { get; set; }
        public string Web { get; set; }
        public string Observacion { get; set; }
        public bool IsReciboInterno { get; set; }
        public bool IsFamiliaProducto { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizacionRetiro> AutorizacionRetiros { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoDocIdentidade TipoDocIdentidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteIngreso> ComprobanteIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstanciaEntrega> ConstanciaEntregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacione> Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetClienteContacto> DetClienteContactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionCliente> DireccionClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturado> Facturados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioNave> InventarioNaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenIngreso> OrdenIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa> Tarifas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaNave> TransferenciaNaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vigilancia> Vigilancias { get; set; }
    }
}
