//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetClienteContacto
    {
        public int IdDetClienteContacto { get; set; }
        public int IdCliente { get; set; }
        public string NombreContacto { get; set; }
        public string Telefono { get; set; }
        public short IdCargo { get; set; }
        public string Email { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
