//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetNotaSalida
    {
        public int IdDetNotaSalida { get; set; }
        public int IdNotaSalida { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
    
        public virtual NotaSalida NotaSalida { get; set; }
    }
}
