//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenIngresosVi
    {
        public int IdDetOrdenIngreso { get; set; }
        public int IdOrdenIngreso { get; set; }
        public short IdNave { get; set; }
        public int IdProducto { get; set; }
        public string DescripcionProducto1 { get; set; }
        public string DescripcionProducto2 { get; set; }
        public string DescripcionProducto3 { get; set; }
        public string DescripcionProducto4 { get; set; }
        public string DescripcionProducto5 { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoNeto { get; set; }
        public decimal Fob { get; set; }
        public decimal Flete { get; set; }
        public decimal Seguro { get; set; }
        public decimal Cif { get; set; }
        public string SeriePoliza { get; set; }
        public string FacturaComercial { get; set; }
        public decimal CantidadComercial { get; set; }
        public short IdUnidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public short IdUnidadFisica { get; set; }
        public string PartidaArancelaria { get; set; }
        public string CodigoProducto { get; set; }
        public string Correlativo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int IdCliente { get; set; }
        public string NumDocTransporte { get; set; }
        public short IdUnidadBulto { get; set; }
        public string NombreUnidadComercial { get; set; }
        public string NombreUnidadFisica { get; set; }
        public string NombreUnidadBulto { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Ano { get; set; }
        public string NombreNave { get; set; }
        public short IdZona { get; set; }
        public string NombreZona { get; set; }
        public string CodigoZona { get; set; }
        public Nullable<System.DateTime> FechaFacturaComercial { get; set; }
        public byte IdTipoCliente { get; set; }
        public string NombreTipoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string CodigoNave { get; set; }
        public decimal CantidadDispBultoGuia { get; set; }
        public decimal CantidadDispComGuia { get; set; }
        public decimal CantidadDispFisGuia { get; set; }
        public decimal CantidadDispComAutRet { get; set; }
        public decimal CantidadBulto { get; set; }
        public decimal CantidadDispBultoAutRet { get; set; }
        public decimal CantidadDispFisAutRet { get; set; }
        public bool IsAduanero { get; set; }
        public bool IsDesglose { get; set; }
        public string NumeroDocumentoRef { get; set; }
        public string NombreAgenciaAduanera { get; set; }
        public string NombreTipoTransporte { get; set; }
        public short IdAgenciaAduanera { get; set; }
        public byte IdTipoTransporte { get; set; }
        public string Dua { get; set; }
        public System.DateTime FechaNumeracionDua { get; set; }
        public short PlazoRegimen { get; set; }
        public short IdTerminalAlmacenamiento { get; set; }
        public string CodigoTerminalAlmacenamiento { get; set; }
        public string NombreTerminalAlmacenamiento { get; set; }
        public Nullable<System.DateTime> FechaVencimientoRegimen { get; set; }
        public string CodigoAgenciaAduanera { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public string DescripcionMercaderia { get; set; }
        public decimal CantidadBultosTotal { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public byte IdTipoMercaderia { get; set; }
        public decimal PesoBrutoDispAutRet { get; set; }
        public decimal FobDispAutRet { get; set; }
        public decimal FleteDispAutRet { get; set; }
        public decimal SeguroDispAutRet { get; set; }
        public decimal CifDispAutRet { get; set; }
    }
}
