//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenIngresoAreaKardexsVi
    {
        public int IdDetOrdenIngresoAreaKardex { get; set; }
        public int IdOrdenIngreso { get; set; }
        public short IdNave { get; set; }
        public decimal Area { get; set; }
        public string NombreNave { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
    }
}
