//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturadosVi
    {
        public int IdFacturado { get; set; }
        public bool IsAnticipoAplicado { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int IdCliente { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal DctoItems { get; set; }
        public decimal DctoTotal { get; set; }
        public decimal Exonerado { get; set; }
        public decimal Inafecto { get; set; }
        public decimal Gravado { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal Anticipo { get; set; }
        public decimal OtrosCargos { get; set; }
        public decimal Gratuito { get; set; }
        public decimal Total { get; set; }
        public decimal Cobrado { get; set; }
        public decimal Saldo { get; set; }
        public string Observacion { get; set; }
        public bool IsAnulado { get; set; }
        public decimal ImporteDetraccion { get; set; }
        public Nullable<System.DateTime> FechaPagoDetraccion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreCliente { get; set; }
        public string NombreTipoCliente { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreCondicionPago { get; set; }
        public string NombreTipoFacturacion { get; set; }
        public string NombreTipoComprobantePago { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public byte IdTipoCliente { get; set; }
        public bool IsAnticipo { get; set; }
        public decimal DctoPorc { get; set; }
        public string NombreMotivoAnulComprobante { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public Nullable<System.DateTime> FechaProgDetraccion { get; set; }
        public string CuentaDetraccion { get; set; }
        public string NombreUsuario { get; set; }
        public string CodigoConcar { get; set; }
        public int IdContrato { get; set; }
        public string Mes { get; set; }
        public decimal TipoCambio { get; set; }
        public byte IdTipoFacturacion { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public byte IdCondicionPago { get; set; }
        public short IdMoneda { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public byte Expr1 { get; set; }
        public short IdUsuario { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
    }
}
