//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int IdParametro { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal PorcDetraccion { get; set; }
        public decimal ImporteDetraccionMayorA { get; set; }
        public short HaberComprasSoles { get; set; }
        public short HaberComprasDolares { get; set; }
        public short DebeVentasSoles { get; set; }
        public short DebeVentasDolares { get; set; }
        public short CuentaContableIgv { get; set; }
        public short HaberReciboHonorariosSoles { get; set; }
        public short HaberReciboHonorariosDolares { get; set; }
        public short DetraccionCompras { get; set; }
        public short CajaSoles { get; set; }
        public short CajaDolares { get; set; }
        public string EmailOc { get; set; }
        public string ClaveEmailOc { get; set; }
        public string EmailCotizaciones { get; set; }
        public string ClaveEmailCotizaciones { get; set; }
        public string EmailContratos { get; set; }
        public string ClaveEmailContratos { get; set; }
        public short IdSeccionCompras { get; set; }
        public string PuertoSerial { get; set; }
        public int Baudios { get; set; }
        public short BitParada { get; set; }
        public string ImpresoraBalanza { get; set; }
        public decimal AprobarPagosAPartir { get; set; }
        public string RutaNubefac { get; set; }
        public string TokenNubefact { get; set; }
        public byte DiasAntFacturacion { get; set; }
        public short IdRubroCalculoM2 { get; set; }
        public decimal ValorUnitarioM2Pormedio { get; set; }
        public byte NumCopiasCE { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual CuentaContable CuentaContable1 { get; set; }
        public virtual CuentaContable CuentaContable2 { get; set; }
        public virtual CuentaContable CuentaContable3 { get; set; }
        public virtual CuentaContable CuentaContable4 { get; set; }
        public virtual CuentaContable CuentaContable5 { get; set; }
        public virtual CuentaContable CuentaContable6 { get; set; }
        public virtual CuentaContable CuentaContable7 { get; set; }
        public virtual CuentaContable CuentaContable8 { get; set; }
        public virtual CuentaContable CuentaContable9 { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Seccione Seccione { get; set; }
    }
}
