//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifasVi
    {
        public int IdTarifa { get; set; }
        public int IdCliente { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreRubro { get; set; }
        public string NombreCliente { get; set; }
        public byte IdTipoCliente { get; set; }
        public string NombreTipoCliente { get; set; }
        public string NombreUsuario { get; set; }
        public decimal PrecioUnitario { get; set; }
        public short IdUsuario { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreMoneda { get; set; }
        public string CodigoMoneda { get; set; }
        public short IdRubro { get; set; }
        public short IdMoneda { get; set; }
    }
}
