//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenciaAduanera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgenciaAduanera()
        {
            this.OrdenIngresos = new HashSet<OrdenIngreso>();
        }
    
        public short IdAgenciaAduanera { get; set; }
        public string NombreAgenciaAduanera { get; set; }
        public string CodigoAgenciaAduanera { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenIngreso> OrdenIngresos { get; set; }
    }
}
