//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacionRetirosVi
    {
        public int IdAutorizacionRetiro { get; set; }
        public string Correlativo { get; set; }
        public bool IsAduanero { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public string NumDocumentoRef { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string DuaNacionalizacion { get; set; }
        public string DuaNacionalizacionResu { get; set; }
        public System.DateTime FechaNumeracion { get; set; }
        public decimal Fob { get; set; }
        public decimal Flete { get; set; }
        public decimal Seguro { get; set; }
        public decimal Cif { get; set; }
        public decimal MontoLiquidado { get; set; }
        public decimal MontoGarantizado { get; set; }
        public decimal MontoCancelado { get; set; }
        public System.DateTime FechaCancelacion { get; set; }
        public byte Canal { get; set; }
        public System.DateTime FecReg { get; set; }
        public string NombreUsuario { get; set; }
        public string CorrelativoOrdenIngreso { get; set; }
        public string NombreCliente { get; set; }
        public string NombreBanco { get; set; }
        public string Dua { get; set; }
        public short IdAgenciaAduanera { get; set; }
        public string NombreAgenciaAduanera { get; set; }
        public Nullable<System.DateTime> FechaVencimientoRegimen { get; set; }
        public string Ano { get; set; }
        public short IdNave { get; set; }
        public string NombreNave { get; set; }
        public string NumeroOrdenAgenciaAduanera { get; set; }
        public decimal CantidadTotal { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public short IdUsuario { get; set; }
        public short IdBanco { get; set; }
        public bool IsAnulada { get; set; }
    }
}
