//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetAutorizacionRetirosVi
    {
        public int IdDetAutorizacionRetiro { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public int IdDetOrdenIngreso { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal Fob { get; set; }
        public decimal Flete { get; set; }
        public decimal Seguro { get; set; }
        public decimal Cif { get; set; }
        public string DescripcionProducto1 { get; set; }
        public string DescripcionProducto2 { get; set; }
        public string DescripcionProducto3 { get; set; }
        public string DescripcionProducto4 { get; set; }
        public string DescripcionProducto5 { get; set; }
        public int IdProducto { get; set; }
        public string CodigoProducto { get; set; }
        public short IdUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public string Correlativo { get; set; }
        public string Ano { get; set; }
        public string CodigoNave { get; set; }
        public string CodigoZona { get; set; }
        public string NombreNave { get; set; }
        public string NombreZona { get; set; }
        public decimal CantidadDispBultoConstEnt { get; set; }
        public decimal CantidadDispComConstEnt { get; set; }
        public decimal CantidadDispFisConstEnt { get; set; }
        public decimal CantidadBulto { get; set; }
        public string SeriePoliza { get; set; }
        public string NombreUnidadBulto { get; set; }
        public short IdUnidadFisica { get; set; }
        public short IdUnidadComercial { get; set; }
        public string SiglaUnidadComercial { get; set; }
        public string NombreUnidadComercial { get; set; }
        public string SiglaUnidadFisica { get; set; }
        public string NombreUnidadFisica { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public short IdNave { get; set; }
        public string NumDocumentoRef { get; set; }
        public string CorrelativoAR { get; set; }
        public string SerieGuia { get; set; }
        public string NumeroGuia { get; set; }
    }
}
