//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetBancoCobroPago
    {
        public int IdDetBancoCobroPago { get; set; }
        public int IdBancoCobroPago { get; set; }
        public short IdCuentaContable { get; set; }
        public string Descripcion { get; set; }
        public string Anexo { get; set; }
        public short IdCentroCosto { get; set; }
        public decimal Importe { get; set; }
        public int IdFacturado { get; set; }
        public int IdNotaDebito { get; set; }
        public int IdCompra { get; set; }
        public int IdReciboHonorario { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual BancoCobroPago BancoCobroPago { get; set; }
        public virtual CentroCosto CentroCosto { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Facturado Facturado { get; set; }
        public virtual NotaDebito NotaDebito { get; set; }
        public virtual ReciboHonorario ReciboHonorario { get; set; }
    }
}
