//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetCompra
    {
        public int IdDetalleCompra { get; set; }
        public int IdCompra { get; set; }
        public int IdArticulo { get; set; }
        public decimal ValorCompra { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal Cantidad { get; set; }
        public decimal DctoPorc { get; set; }
        public decimal TotalItem { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
