//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetConstanciaEntregaArea
    {
        public int IdDetConstanciaEntregaArea { get; set; }
        public int IdConstanciaEntrega { get; set; }
        public short IdNave { get; set; }
        public decimal AreaLiberada { get; set; }
    
        public virtual ConstanciaEntrega ConstanciaEntrega { get; set; }
        public virtual Nave Nave { get; set; }
    }
}
