//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetTransferenciasVi
    {
        public int IdDetTransferencia { get; set; }
        public int IdTransferencia { get; set; }
        public int IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal ValorUnitario { get; set; }
        public short IdOrigen { get; set; }
        public short IdDestino { get; set; }
        public System.DateTime FechaTransferencia { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public string Observacion { get; set; }
        public string NombreArticulo { get; set; }
        public int IdUnidad { get; set; }
        public string NombreUnidad { get; set; }
        public string SeccionOrigen { get; set; }
        public string SeccionDestino { get; set; }
    }
}
