//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaRemisionsVi
    {
        public int IdGuiaRemision { get; set; }
        public string Observacion { get; set; }
        public string PrecintoOrigen { get; set; }
        public string PrecintoSupervision { get; set; }
        public string PrecintoAduana { get; set; }
        public byte IdTipoContenedor { get; set; }
        public short CantidadPaletas { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreCliente { get; set; }
        public string NombreTipoContenedor { get; set; }
        public int IdOrdenIngreso { get; set; }
        public string NumOrdenIngreso { get; set; }
        public bool CerradaOrdenIngreso { get; set; }
        public string NombreUsuario { get; set; }
        public string NumeroContenedor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal CantidadBuenos { get; set; }
        public decimal CantidadMalos { get; set; }
        public short IdAtendidoPor { get; set; }
        public string AtendidoPor { get; set; }
        public string NumeroLicencia { get; set; }
        public string NombreConductor { get; set; }
        public string DniConductor { get; set; }
        public short IdLicencia { get; set; }
        public string Placa { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Permanencia { get; set; }
        public string SerieGuia { get; set; }
        public int IdVigilancia { get; set; }
        public int IdDetVigilanciaGuia { get; set; }
        public int IdCliente { get; set; }
        public string NumeroGuia { get; set; }
        public string Ano { get; set; }
        public decimal PesoBrutoTotal { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public decimal CantidadBultos { get; set; }
        public short IdUsuario { get; set; }
        public System.DateTime Expr1 { get; set; }
        public string DescripcionMercaderia { get; set; }
        public string NumeroDocumentoRef { get; set; }
        public bool IsAduanero { get; set; }
        public short IdUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public short IdEmpresaTransporte { get; set; }
        public string NombreEmpresaTransporte { get; set; }
        public byte IdTipoIngreso { get; set; }
        public string NombreTipoIngreso { get; set; }
        public string CodigoNave { get; set; }
        public string NombreNave { get; set; }
        public decimal BultosDeclarados { get; set; }
    }
}
