//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaDebitosVi
    {
        public int IdNotaDebito { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Descripcion { get; set; }
        public decimal TipoCambio { get; set; }
        public int IdFacturado { get; set; }
        public decimal Exonerado { get; set; }
        public decimal Inafecto { get; set; }
        public decimal Gravado { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal Total { get; set; }
        public decimal Cobrado { get; set; }
        public decimal Saldo { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreTipoNotaDebito { get; set; }
        public string NombreMotivoAnulComprobante { get; set; }
        public string NombreCliente { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string SimboloMoneda { get; set; }
        public string SerieRef { get; set; }
        public string NumdocRef { get; set; }
        public System.DateTime FechaEmisionFacturado { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public decimal TotalRef { get; set; }
        public int IdCliente { get; set; }
        public string NombreUsuario { get; set; }
        public byte IdTipoComprobantePagoFacturado { get; set; }
        public string CodigoConcarFacturado { get; set; }
        public string CodigoTipoComprobantePagoFacturado { get; set; }
        public decimal MontoIgvFacturado { get; set; }
        public decimal PorcIgvFacturado { get; set; }
        public decimal GravadoFacturado { get; set; }
        public decimal InafectoFacturado { get; set; }
        public decimal ExoneradoFacturado { get; set; }
        public short IdCuentaContableDescripcion { get; set; }
        public short IdMoneda { get; set; }
        public short IdUsuario { get; set; }
        public byte IdTipoNotaDebito { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
    }
}
