//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaDebito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaDebito()
        {
            this.ComprobanteIngresos = new HashSet<ComprobanteIngreso>();
            this.DetBancoCobroPagos = new HashSet<DetBancoCobroPago>();
        }
    
        public int IdNotaDebito { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public byte IdTipoNotaDebito { get; set; }
        public string Descripcion { get; set; }
        public short IdCuentaContableDescripcion { get; set; }
        public decimal TipoCambio { get; set; }
        public int IdFacturado { get; set; }
        public decimal Exonerado { get; set; }
        public decimal Inafecto { get; set; }
        public decimal Gravado { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal Total { get; set; }
        public decimal Cobrado { get; set; }
        public decimal Saldo { get; set; }
        public bool IsAnulado { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteIngreso> ComprobanteIngresos { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetBancoCobroPago> DetBancoCobroPagos { get; set; }
        public virtual Facturado Facturado { get; set; }
        public virtual MotivoAnulComprobante MotivoAnulComprobante { get; set; }
        public virtual TipoNotaDebito TipoNotaDebito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
