//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaSalida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaSalida()
        {
            this.DetNotaSalidas = new HashSet<DetNotaSalida>();
        }
    
        public int IdNotaSalida { get; set; }
        public string Correla { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public int IdDestino { get; set; }
        public short IdSeccion { get; set; }
        public string Observacion { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetNotaSalida> DetNotaSalidas { get; set; }
        public virtual OrigenDestino OrigenDestino { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
