//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenIngreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenIngreso()
        {
            this.ActaAperturas = new HashSet<ActaApertura>();
            this.DetOrdenIngresoAreaKardexs = new HashSet<DetOrdenIngresoAreaKardex>();
            this.DetOrdenIngresoAreas = new HashSet<DetOrdenIngresoArea>();
            this.DetOrdenIngresoCertificadoDepositos = new HashSet<DetOrdenIngresoCertificadoDeposito>();
            this.DetOrdenIngresos = new HashSet<DetOrdenIngreso>();
            this.GuiaRemisions = new HashSet<GuiaRemision>();
            this.Pesados = new HashSet<Pesado>();
            this.ServicioPrestados = new HashSet<ServicioPrestado>();
        }
    
        public int IdOrdenIngreso { get; set; }
        public bool IsCerrada { get; set; }
        public string Correlativo { get; set; }
        public string Ano { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool IsAduanero { get; set; }
        public short IdNave { get; set; }
        public int IdCliente { get; set; }
        public string DescripcionMercaderia { get; set; }
        public decimal CantidadBultos { get; set; }
        public short IdUnidadBulto { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoNeto { get; set; }
        public decimal TotalFob { get; set; }
        public decimal TotalFlete { get; set; }
        public decimal TotalSeguro { get; set; }
        public decimal TotalCif { get; set; }
        public string NumeroDocumentoRef { get; set; }
        public short IdAgenciaAduanera { get; set; }
        public string NumeroOrdenAgenciaAduanera { get; set; }
        public decimal AreaOcupada { get; set; }
        public decimal AreaKardex { get; set; }
        public bool IsAreaFija { get; set; }
        public byte IdTipoIngreso { get; set; }
        public string Observacion { get; set; }
        public short IdPais { get; set; }
        public string Dua { get; set; }
        public string DuaNacionalizacionResu { get; set; }
        public System.DateTime FechaNumeracionDua { get; set; }
        public short PlazoRegimen { get; set; }
        public Nullable<System.DateTime> FechaVencimientoRegimen { get; set; }
        public byte IdTipoTransporte { get; set; }
        public short IdEmpresaTransporte { get; set; }
        public string Manifiesto { get; set; }
        public string NumDocTransporte { get; set; }
        public short IdTerminalAlmacenamiento { get; set; }
        public System.DateTime FecReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActaApertura> ActaAperturas { get; set; }
        public virtual AgenciaAduanera AgenciaAduanera { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngresoAreaKardex> DetOrdenIngresoAreaKardexs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngresoArea> DetOrdenIngresoAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngresoCertificadoDeposito> DetOrdenIngresoCertificadoDepositos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenIngreso> DetOrdenIngresos { get; set; }
        public virtual EmpresaTransporte EmpresaTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiaRemision> GuiaRemisions { get; set; }
        public virtual Nave Nave { get; set; }
        public virtual TerminalAlmacenamiento TerminalAlmacenamiento { get; set; }
        public virtual TipoIngreso TipoIngreso { get; set; }
        public virtual TipoTransporte TipoTransporte { get; set; }
        public virtual UnidadBulto UnidadBulto { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pesado> Pesados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioPrestado> ServicioPrestados { get; set; }
    }
}
