//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenIngresosVi
    {
        public int IdOrdenIngreso { get; set; }
        public string Correlativo { get; set; }
        public bool IsAduanero { get; set; }
        public short IdNave { get; set; }
        public int IdCliente { get; set; }
        public string DescripcionMercaderia { get; set; }
        public decimal TotalFob { get; set; }
        public decimal TotalFlete { get; set; }
        public decimal TotalSeguro { get; set; }
        public decimal TotalCif { get; set; }
        public string NumeroOrdenAgenciaAduanera { get; set; }
        public decimal AreaOcupada { get; set; }
        public string Observacion { get; set; }
        public short IdPais { get; set; }
        public string Dua { get; set; }
        public System.DateTime FechaNumeracionDua { get; set; }
        public short PlazoRegimen { get; set; }
        public short IdTerminalAlmacenamiento { get; set; }
        public string Manifiesto { get; set; }
        public string NumDocTransporte { get; set; }
        public System.DateTime FecReg { get; set; }
        public string NombreNave { get; set; }
        public string NombreCliente { get; set; }
        public string NombreTipoIngreso { get; set; }
        public string NombrePais { get; set; }
        public string NombreTipoTransporte { get; set; }
        public string NombreTerminalAlmacenamiento { get; set; }
        public string NombreUsuario { get; set; }
        public string NumeroDocumentoRef { get; set; }
        public bool IsCerrada { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal CantidadBultos { get; set; }
        public string NombreAgenciaAduanera { get; set; }
        public string CodigoAgenciaAduanera { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string NombreEmpresaTransporte { get; set; }
        public string CodigoEmpresaTransporte { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoNeto { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public short IdEmpresaTransporte { get; set; }
        public Nullable<System.DateTime> FechaVencimientoRegimen { get; set; }
        public short IdAgenciaAduanera { get; set; }
        public string Ano { get; set; }
        public string CodigoTerminalAlmacenamiento { get; set; }
        public short IdUnidadBulto { get; set; }
        public string SiglaUnidadBulto { get; set; }
        public string NombreUnidadBulto { get; set; }
        public string DuaNacionalizacionResu { get; set; }
        public short IdUsuario { get; set; }
        public string CodigoNave { get; set; }
        public bool IsAreaFija { get; set; }
        public int DiasPago { get; set; }
        public byte IdTipoIngreso { get; set; }
        public byte IdTipoTransporte { get; set; }
        public decimal AreaKardex { get; set; }
    }
}
