//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VigilanciasVi
    {
        public int IdVigilancia { get; set; }
        public int IdCliente { get; set; }
        public string Placa { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Permanencia { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreCliente { get; set; }
        public string NombreUsuario { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public short IdLicencia { get; set; }
        public string NumeroLicencia { get; set; }
        public string NombreConductor { get; set; }
        public string DniConductor { get; set; }
        public short IdUsuario { get; set; }
        public byte TipoOperacion { get; set; }
        public bool IsSalida { get; set; }
    }
}
