//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesVi
    {
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string CuentaDetraccion { get; set; }
        public string Web { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreTipoCliente { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public int DiasPago { get; set; }
        public string CodigoTipoDocIdentidad { get; set; }
        public string Telefono { get; set; }
        public bool IsReciboInterno { get; set; }
        public string NombreUsuario { get; set; }
        public string NombrePais { get; set; }
        public short IdPais { get; set; }
        public string PartidaElectrónica { get; set; }
        public string RepresentanteLegal { get; set; }
        public string DniRepresentanteLegal { get; set; }
        public short IdUsuario { get; set; }
        public bool IsFamiliaProducto { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public byte IdTipoCliente { get; set; }
    }
}
