//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteEgresosVi
    {
        public int IdComprobanteEgreso { get; set; }
        public string NumdocComprobante { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int IdCompra { get; set; }
        public decimal Importe { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreConcepto { get; set; }
        public string NombreMedioPago { get; set; }
        public string NombreCaja { get; set; }
        public string NombreMotivoAnulComprobante { get; set; }
        public string SimboloMoneda { get; set; }
        public string NumdocCompra { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public int IdProveedor { get; set; }
        public string Serie { get; set; }
        public short IdEmpleado { get; set; }
        public int IdReciboHonorario { get; set; }
        public string NumeroReciboHonorarios { get; set; }
        public decimal TipoCambio { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public System.DateTime VencimientoCompra { get; set; }
        public System.DateTime FechaReciboHonorarios { get; set; }
        public System.DateTime VencimientoReciboHonorarios { get; set; }
        public string NombreUsuario { get; set; }
        public string RazonSocial { get; set; }
        public byte IdTipoDocIdentidadProveedor { get; set; }
        public string NumeroDocIdentidadProveedor { get; set; }
        public string NombreCortoTipoDocIdentidadProveedor { get; set; }
        public string CodigoTipoDocIdentidadProveedor { get; set; }
        public string NombreEmpleado { get; set; }
        public byte IdTipoDocIdentidadEmpleado { get; set; }
        public string NumeroDocIdentidadEmpleado { get; set; }
        public string NombreCortoTipoDocIdentidadEmpleado { get; set; }
        public string CodigoTipoDocIdentidadEmpleado { get; set; }
        public string NombreRubro { get; set; }
        public short Expr1 { get; set; }
        public short IdRubro { get; set; }
        public short IdGrupoPago { get; set; }
        public string NombreGrupoPago { get; set; }
        public string CodigoMedioPago { get; set; }
        public string NombreTipoComprobantePago { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public string CodigoConcar { get; set; }
        public short IdUsuario { get; set; }
        public short IdMotivoAnulComprobante { get; set; }
        public short IdMedioPago { get; set; }
        public short IdCaja { get; set; }
        public short IdMoneda { get; set; }
    }
}
