//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desglos
    {
        public int IdDesglose { get; set; }
        public int IdDetOrdenIngresoOrigen { get; set; }
        public decimal CantidadOrigen { get; set; }
        public int IdDetOrdenIngresoDestino { get; set; }
        public decimal CantidadDestino { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual DetOrdenIngreso DetOrdenIngreso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
