//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetAutorizacionRetiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetAutorizacionRetiro()
        {
            this.DetConstanciaEntregas = new HashSet<DetConstanciaEntrega>();
            this.DetVigilanciaGuias = new HashSet<DetVigilanciaGuia>();
        }
    
        public int IdDetAutorizacionRetiro { get; set; }
        public int IdAutorizacionRetiro { get; set; }
        public int IdDetOrdenIngreso { get; set; }
        public string SerieGuia { get; set; }
        public string NumeroGuia { get; set; }
        public decimal CantidadBulto { get; set; }
        public decimal CantidadDispBultoConstEnt { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadDispComConstEnt { get; set; }
        public decimal CantidadFisica { get; set; }
        public decimal CantidadDispFisConstEnt { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal Fob { get; set; }
        public decimal Flete { get; set; }
        public decimal Seguro { get; set; }
        public decimal Cif { get; set; }
    
        public virtual AutorizacionRetiro AutorizacionRetiro { get; set; }
        public virtual DetOrdenIngreso DetOrdenIngreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetConstanciaEntrega> DetConstanciaEntregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetVigilanciaGuia> DetVigilanciaGuias { get; set; }
    }
}
