//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetGuiaRemision
    {
        public int IdDetGuiaRemision { get; set; }
        public int IdGuiaRemision { get; set; }
        public int IdDetOrdenIngreso { get; set; }
        public decimal CantidadBuenos { get; set; }
        public decimal CantidadMalos { get; set; }
        public decimal CantidadBultos { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public short CantidadPaletas { get; set; }
        public string Observacion { get; set; }
    
        public virtual DetOrdenIngreso DetOrdenIngreso { get; set; }
        public virtual GuiaRemision GuiaRemision { get; set; }
    }
}
