//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloOperacionesVi
    {
        public int IdModuloOperacion { get; set; }
        public int IdModulo { get; set; }
        public int IdOperacion { get; set; }
        public string NombreModulo { get; set; }
        public string NombreOperacion { get; set; }
        public bool Sel { get; set; }
        public string NombreUsuario { get; set; }
        public string AliasUsuario { get; set; }
        public string Password { get; set; }
        public short IdUsuario { get; set; }
    }
}
