//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenComprasVi
    {
        public int IdOrdenCompra { get; set; }
        public string Correla { get; set; }
        public bool IsEmailEnviado { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal ValorVenta { get; set; }
        public decimal PorcIgv { get; set; }
        public decimal MontoIgv { get; set; }
        public decimal Monto { get; set; }
        public string Observacion { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string NombreMedioPago { get; set; }
        public string NombreCondicionPago { get; set; }
        public string SimboloMoneda { get; set; }
        public short IdMotivoAnulOc { get; set; }
        public string NombreMotivoAnulOc { get; set; }
        public string CotizacionReferencial { get; set; }
        public int IdRequriemientoProducto { get; set; }
        public string NumReqProd { get; set; }
        public string NombreUsuario { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string Direccion { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public string NombreEmpleado { get; set; }
        public string NombreSeccion { get; set; }
        public short IdSubArea { get; set; }
        public short IdArea { get; set; }
        public string NombreSubArea { get; set; }
        public string NombreArea { get; set; }
        public short IdCargo { get; set; }
        public string NombreCargo { get; set; }
        public short IdSeccion { get; set; }
        public int IdEmpleado { get; set; }
        public int IdProveedor { get; set; }
        public short IdMoneda { get; set; }
        public byte IdCondicionPago { get; set; }
        public short IdMedioPago { get; set; }
        public short IdUsuario { get; set; }
    }
}
