//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vigilancia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vigilancia()
        {
            this.ConstanciaEntregas = new HashSet<ConstanciaEntrega>();
            this.DetVigilanciaGuias = new HashSet<DetVigilanciaGuia>();
        }
    
        public int IdVigilancia { get; set; }
        public byte TipoOperacion { get; set; }
        public int IdCliente { get; set; }
        public short IdLicencia { get; set; }
        public string Placa { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public string Permanencia { get; set; }
        public bool IsSalida { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstanciaEntrega> ConstanciaEntregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetVigilanciaGuia> DetVigilanciaGuias { get; set; }
        public virtual Licencia Licencia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
