//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratosVi
    {
        public int IdContrato { get; set; }
        public short Renovacion { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public short IdMoneda { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public string Observacion { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreUsuario { get; set; }
        public string SimboloMoneda { get; set; }
        public string NombreCliente { get; set; }
        public byte IdTipoDocIdentidad { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string NombreCortoTipoDocIdentidad { get; set; }
        public string CorrelativoCotizacion { get; set; }
        public int IdCotizacion { get; set; }
        public string NombreMotivoAnulContrato { get; set; }
        public decimal Area { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal ImporteTotal { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public decimal TarifaServicioExtraordinarioHora { get; set; }
        public decimal TarifaDescarga20 { get; set; }
        public decimal TarifaDescarga40 { get; set; }
        public decimal TarifaMontaCarga { get; set; }
        public string PartidaElectrónica { get; set; }
        public string RepresentanteLegal { get; set; }
        public string DniRepresentanteLegal { get; set; }
        public string NombreMoneda { get; set; }
        public bool IsEnviado { get; set; }
        public string Email1 { get; set; }
        public string CorrelatiovContrato { get; set; }
        public short IdUsuario { get; set; }
        public short IdMotivoAnulContrato { get; set; }
    }
}
