//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionesVi
    {
        public int IdCotizacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCliente { get; set; }
        public string Atencion { get; set; }
        public string Referencia { get; set; }
        public short IdEmpleado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string NombreCliente { get; set; }
        public string NombreEmpleado { get; set; }
        public string NombreUsuario { get; set; }
        public string Correlativo { get; set; }
        public bool IsAnulada { get; set; }
        public string NombreAgente { get; set; }
        public short IdAgente { get; set; }
        public decimal TarifaMinimaServicioAdicional { get; set; }
        public decimal PrecioUnitarioPicking { get; set; }
        public decimal TarifaServicioExtraordinarioHora { get; set; }
        public decimal TarifaCargaPisoPaletas { get; set; }
        public decimal TarifaCargaRacks { get; set; }
        public decimal TarifaCargaFurgones { get; set; }
        public decimal TarifaCargaPlataforma { get; set; }
        public decimal TarifaDescarga40 { get; set; }
        public decimal TarifaDescarga20 { get; set; }
        public decimal TarifaMinimaSeguroMes { get; set; }
        public decimal TarifaPaleta { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Area { get; set; }
        public string SimboloMoneda { get; set; }
        public decimal PorcTarifaSegurorMes { get; set; }
        public decimal PrecioUnitarioPaletizado { get; set; }
        public string NombreCargo { get; set; }
        public short IdCargo { get; set; }
        public string Email1 { get; set; }
        public bool IsEnviada { get; set; }
        public bool IsAceptada { get; set; }
        public decimal FacturacionMinimaMes { get; set; }
        public short IdUsuario { get; set; }
        public short IdMoneda { get; set; }
    }
}
