//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBanco()
        {
            this.BancoCobroPagos = new HashSet<BancoCobroPago>();
        }
    
        public short IdCuentaBanco { get; set; }
        public short IdBanco { get; set; }
        public string NumCuenta { get; set; }
        public short IdMoneda { get; set; }
        public bool IsDetraccion { get; set; }
        public bool IsActiva { get; set; }
        public bool IsImprimirEnFac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancoCobroPago> BancoCobroPagos { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
