//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetConstanciaEntrega
    {
        public int IdDetConstanciaEntrega { get; set; }
        public int IdConstanciaEntrega { get; set; }
        public int IdDetAutorizacionRetiro { get; set; }
        public decimal CantidadBulto { get; set; }
        public decimal CantidadComercial { get; set; }
        public decimal CantidadFisica { get; set; }
        public short CantidadPaletas { get; set; }
        public string Observacion { get; set; }
    
        public virtual ConstanciaEntrega ConstanciaEntrega { get; set; }
        public virtual DetAutorizacionRetiro DetAutorizacionRetiro { get; set; }
    }
}
