//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetFacturadosVi
    {
        public int IdDetFacturado { get; set; }
        public int IdFacturado { get; set; }
        public short IdRubro { get; set; }
        public decimal Cantidad { get; set; }
        public decimal ValorVentaUnit { get; set; }
        public decimal SubTotalVenta { get; set; }
        public decimal DctoPorc { get; set; }
        public decimal TotDctoItem { get; set; }
        public decimal ValorVentaTotal { get; set; }
        public byte IdTipoIgv { get; set; }
        public decimal PorcIgvItem { get; set; }
        public decimal MontoIgvItem { get; set; }
        public decimal TotalItem { get; set; }
        public int IdFacturadoAnticipo { get; set; }
        public byte IdTipoComprobantePago { get; set; }
        public string Serie { get; set; }
        public string Numdoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int IdCliente { get; set; }
        public short IdMoneda { get; set; }
        public decimal TipoCambio { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public bool IsAnulado { get; set; }
        public string NumeroDocIdentidad { get; set; }
        public string CodigoTipoComprobantePago { get; set; }
        public string NombreCliente { get; set; }
        public decimal TotalFactura { get; set; }
        public string NombreRubro { get; set; }
        public short IdCuentaContable { get; set; }
        public string NumeroCuentaContable { get; set; }
        public string NombreCuentaContable { get; set; }
        public decimal MontoIgvFactura { get; set; }
        public decimal Gravado { get; set; }
        public bool IsServicio { get; set; }
        public short IdUnidad { get; set; }
        public string Observacion { get; set; }
    }
}
