//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetRequerimientoProducto
    {
        public int IdDetRequerimientoProducto { get; set; }
        public int IdRequerimientoProducto { get; set; }
        public int IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal MontoReferencial { get; set; }
        public bool IsOrdenCompra { get; set; }
    
        public virtual RequerimientoProducto RequerimientoProducto { get; set; }
    }
}
