//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferenciaNave
    {
        public int IdTransferenciaNave { get; set; }
        public System.DateTime Fecha { get; set; }
        public short IdNaveOrigen { get; set; }
        public short IdNaveDestino { get; set; }
        public int IdCliente { get; set; }
        public decimal Area { get; set; }
        public short IdMotivoTransferenciaNave { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual MotivoTransferenciaNave MotivoTransferenciaNave { get; set; }
        public virtual Nave Nave { get; set; }
        public virtual Nave Nave1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
