//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transferencia()
        {
            this.DetTransferencias = new HashSet<DetTransferencia>();
        }
    
        public int IdTransferencia { get; set; }
        public short IdOrigen { get; set; }
        public short IdDestino { get; set; }
        public System.DateTime FechaTransferencia { get; set; }
        public decimal ValorTransferencia { get; set; }
        public string Observacion { get; set; }
        public bool IsAprobado { get; set; }
        public bool IsAnulado { get; set; }
        public System.DateTime FechaReg { get; set; }
        public short IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetTransferencia> DetTransferencias { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
